### ISSUE TITLE
Add filter for dinner-only meals

### ISSUE THREAD

**Issue by vvvt** [vvvt/foodi#11]
**Option A**
* add a note saying that a meal is only available for dinner

**Option B**
* add a time-based filter, removing dinner-only meals until they are available

**Comment by SoulKa** [comment]
I prefer Option A since we would need a specific time to switch between evening meals and normal meals.
Despite the option the `Meal` class now has a boolean property `isEveningMeal` (in backend branch).

**Comment by SoulKa** [comment]
fixed with commit a5f70a5bb147c0e21ed4cf032de51d0653d67185 some time ago in branch `front-end`
