### ISSUE TITLE
Adapt to iOS settings style

### ISSUE THREAD

**Issue by vvvt** [vvvt/foodi#14]
Try adding horizontal lines between items

**Comment by SoulKa** [comment]
I can upload iOS screenshots when they are needed for testing

**Comment by vvvt** [comment]
Would be much appreciated

**Comment by SoulKa** [comment]
from the current App screens, the iOS typical settings or should I try to design them iOS like and provide screenshots then?:D

**Comment by vvvt** [comment]
I'd say iOS typical settings

**Comment by SoulKa** [comment]
![with description](https://i.imgur.com/33tKzCi.png)
![without description](https://i.imgur.com/Fw0XvUR.png)

**Comment by SoulKa** [comment]
I don't have an iPhone anymore so I'll close this issue for now :D
