### ISSUE TITLE
Fix display of allergies

### ISSUE THREAD

**Issue by vvvt** [vvvt/foodi#15]

**Comment by SoulKa** [comment]
fixed it but it looks bad. Since there are a lot af allergenes and additives in a meal it is flooding the view. It would be nice to somehow show and hide them on demand (eg. when pressing on "allergenes").

![](https://i.imgur.com/fEKA3VJ.png)

**Comment by SoulKa** [comment]
we could also add some tiny icons for "vegan", "vegetarian", "beef", ...

**Comment by SoulKa** [comment]
fixed by commit 4756783700cf3722be2e5f5929dc760249e7cb13
