### ISSUE TITLE
Setting icon size crashes the app

### ISSUE THREAD

**Issue by vvvt** [vvvt/foodi#17]
When trying to change the [size](https://react-native-elements.github.io/react-native-elements/docs/icon.html#size) of an icon from react-native-elements, the application crashes.

**Comment by SoulKa** [comment]
works for me. I used:
`<Icon size={10} />`
where 10 is a number and not a string

Edit: What is the error message?

**Comment by SoulKa** [comment]
acutally Expo.io recommends to use icons from their [own package](https://docs.expo.io/versions/latest/guides/icons/).

**Comment by vvvt** [comment]
Switched to the Expo icon package
