### ISSUE TITLE
Get Google Maps API-Key

### ISSUE THREAD

**Issue by vvvt** [vvvt/foodi#18]

**Comment by SoulKa** [comment]
did the generated API key work?

**Comment by vvvt** [comment]
The app doesn't crash anymore when selecting the map. However it doesn't show a map either.

**Comment by SoulKa** [comment]
did you try to select "android only" for the API Key in your google account?

**Comment by vvvt** [comment]
Added restriction to the API-Key. The build still doesn't show a map.

**Comment by SoulKa** [comment]
did you regenerate the API key after changing to "android only" and rebuilt the app with the new key?

**Comment by vvvt** [comment]
Works now after explicitly enabling the Maps SDK. There was an option to enable it without adding any payment information.
